import type { Metadata } from 'next';
import { Geist, Geist_Mono, Montserrat } from 'next/font/google';
import './globals.css';
import { Sidebar } from '@/components/Sidebar';
import { Navbar } from '@/components/Navbar';
import { cookies, headers } from 'next/headers';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const montserrat = Montserrat({
  variable: '--font-montserrat',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const isAuthenticated = false;
  // const path = cookieStore.get('currentPath')?.value;

  const headersList = await headers();
  const path = headersList.get('x-invoke-path') ?? headersList.get('x-next-url');

  // console.log(headersList);

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${montserrat.variable} antialiased`}
      >
        {isAuthenticated ? (
          <div className="font-sans grid grid-cols-[200px_1fr] items-center justify-items-center min-h-screen pb-20">
            <Sidebar />
            <main className="h-screen w-full flex flex-col sm:items-start">
              <Navbar />
              {children}
            </main>
          </div>
        ) : (
          children
        )}
      </body>
    </html>
  );
}
